### ISSUE TITLE
Animating Constraints

### ISSUE THREAD

**Issue by ghost** [wxxsw/POP-SnapKit#2]
I'm having trouble figuring out how to use snap kit + POP from your example. What I'm trying to do is animate a UIView from offscreen to the bottom of the main view while updating to the new constraints.

I have a UIVIew, and I initially am setting it to be offscreen:

```
searchBackGroundView.snp_makeConstraints { (make) in
    make.centerX.equalTo(view.snp_centerX)
    make.left.equalTo(view.snp_left).offset(20)
    make.height.equalTo(50)
    make.right.equalTo(view.snp_right).offset(-20)
    self.searchViewYConstraint = make.centerY.equalTo(view.snp_bottom).offset(30).constraint
}
```

If you could help me figure out the rest, I've tried everything and can't wrap my head around it. Thanks in advance!

**Comment by wxxsw** [comment]
Try this code：

``` swift
let animation = POPSpringAnimation(propertyNamed: kPOPLayoutConstraintConstant)
    animation.springBounciness = 16
    animation.toValue = -40
self.searchViewYConstraint?.layoutConstraint?.pop_addAnimation(animation, forKey: nil)
```

You can set `springBounciness` to change the bounce，set `toValue` to change the `constant` of your constraint.

By the way, you have set the left and right constraints of `searchBackGroundView`, so the x position is known, `make.centerX.equalTo(view.snp_centerX)` is not needed.

Good luck.

**Comment by ghost** [comment]
Yea this worked. Thanks for the help and your work!
